### ISSUE TITLE
Refactor the conditions L27-L31

### ISSUE THREAD

**Issue by c3ho** [strawberries73/OSD600-Journey-on-rocky-trails#1]
https://github.com/strawberries73/OSD600-Journey-on-rocky-trails/blob/33f18323d6f5681b1a22e167953063e6f77077ed/CommandToolLinkCheck/CommandTool/index.js#L27-L31

Apologize for the picture, but in case you missed it in the thread:
![image](https://user-images.githubusercontent.com/18711727/94326123-23c8be80-ff70-11ea-835b-c6368093f768.png)

**Comment by PedroFonsecaDEV** [comment]
![FA7040F6-4869-41CE-8E24-09AFC2B63534](https://user-images.githubusercontent.com/60857409/94403406-612d7780-013b-11eb-90bf-3956b0e0c4a8.jpeg)

@c3ho @strawberries73 

It seems that some terminals are colouring res.status(200) by default. As the URLs are not being coloured. If I'm wrong, could you please explain to us how are you colouring the outputs?  Because we are not seeing how this is happening. 

Thanks.

**Comment by strawberries73** [comment]
Thank you for your input.  This is my fault because I forgot to add npm install colors into the README.  I will fix this.

**Comment by strawberries73** [comment]
@c3ho   Since our lab is about refactoring and I had made the changes you suggested.  I also removed some comments and took out an unused "const colors".  Would you be willing to take a look and perhaps made any suggestions?

**Comment by strawberries73** [comment]
Thank you both for your input.  I have finished improving on my code.
